Update tioNelScript

diff --git a/tioNelScript b/tioNelScript
--- a/tioNelScript
+++ b/tioNelScript
@@ -1,9 +1,9 @@
 #!/bin/bash
-#CREADOR el_tioNel | 15/09/2026 | MOD tioNelScript
-#Alias: @el_tioNel
-# -*- CODIFICACIÓN: UTF-8 -*-
+#CREADOR Henry Chumo | 25/08/2022 | MOD PandaScript
+#Alias : @ChumoGH
+# -*- ENCODING: UTF-8 -*-
 export PATH=$PATH:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/sbin:/bin:/usr/games;
-fecha=`fecha +"%d-%m-%y"`;
+fecha=`date +"%d-%m-%y"`;
 SCPdir="/etc/adm-lite"
 SCPinstal="$HOME/install"
 # Repositorio GitHub del proyecto
@@ -17,38 +17,38 @@ apt-get install curl -y &>/dev/null
 apt install sudo -y &> /dev/null
 mkdir -p /bin/ejecutar
 [[ -e /bin/ejecutar/msg ]] || wget -q -O /bin/ejecutar/msg "${GITHUB_RAW}/Otros/msg"
-fuente /bin/ejecutar/msg > /dev/null 2>&1
+source /bin/ejecutar/msg > /dev/null 2>&1
 COLS=$(tput cols)
 
 os_system() {
- sistema=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/ //')
+ system=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/      //')
  distro=$(echo "$system"|awk '{print $1}')
- caso $distro en
+ case $distro in
  Debian)vercion=$(echo $system|awk '{print $3}'|cut -d '.' -f1);;
  Ubuntu)vercion=$(echo $system|awk '{print $2}'|cut -d '.' -f1,2);;
  esac
  link="https://raw.githubusercontent.com/karl1999x/PandaScript/main/Source-List/${vercion}.list"
 }
 
-si ! [ $(id -u) = 0 ]; entonces
-    claro
-    eco ""
-    eco " _________________________________________________"
-    echo "¡Error fatal!"
-    eco " _________________________________________________"
-    echo "Este script debe ejecutarse como root!"
-    eco " _________________________________________________"
+if ! [ $(id -u) = 0 ]; then
+    clear
+    echo ""
+    echo " _________________________________________________"
+    echo "	Error Fatal!!"
+    echo " _________________________________________________"
+    echo " Este script debe ejecutarse como root!"
+    echo " _________________________________________________"
     echo " Como Solucionarlo "
-    echo "Ejecuta el script como:"
-    echo " ( sudo -i )"
-    echo " sudo su"
-    eco " Retornando . . ."
-    echo $(fecha)
-    Salida 1
+    echo " Ejecuta el script como:"
+    echo "                              (  sudo -i )"
+    echo "	                                sudo su"
+    echo "	                             Retornando . . ."
+    echo $(date)
+    exit 1
 fi
 
 act_ufw() {
-    [[ -f "/usr/sbin/ufw" ]] && ufw permitir 81/tcp; ufw permite 8888/tcp
+    [[ -f "/usr/sbin/ufw" ]] && ufw allow 81/tcp ; ufw allow 8888/tcp
 }
 
 fun_ip () {
@@ -57,23 +57,23 @@ fun_ip () {
     [[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
 }
 
-función_verificar() {
-    echo "verificar" > $(echo -e $(echo 2f62696e2f766572696679737973|sed 's/../\\x&/g;s/$/ /'))
-    echo 'MOD @tioNelScript' > $(echo -e $(echo 2F7573722F6C69622F6C6963656E6365|sed 's/../\\x&/g;s/$/ /'))
+function_verify () {
+    echo "verify" > $(echo -e $(echo 2f62696e2f766572696679737973|sed 's/../\\x&/g;s/$/ /'))
+    echo 'MOD @ChumoGH Joaquin' > $(echo -e $(echo 2F7573722F6C69622F6C6963656E6365|sed 's/../\\x&/g;s/$/ /'))
     [[ $(dpkg --get-selections|grep -w "libpam-cracklib"|head -1) ]] || apt-get install libpam-cracklib -y &> /dev/null
-    echo -e '# Módulo @el_tioNel
-contraseña [éxito=1 predeterminado=ignorar] pam_unix.so sha512 oscuro
-Requisito de contraseña pam_deny.so
-Se requiere contraseña pam_permit.so' > /etc/pam.d/common-password && chmod +x /etc/pam.d/common-password
+    echo -e '# Modulo @ChumoGH
+password [success=1 default=ignore] pam_unix.so obscure sha512
+password requisite pam_deny.so
+password required pam_permit.so' > /etc/pam.d/common-password && chmod +x /etc/pam.d/common-password
 }
 
-valid_fun() {
-    barra de mensajes
-    echo -e "${cor[2]}\n\033[1;37m Script Patrocinado por: @el_tioNel - tioNelScript" | pv-qL 12
-    barra de mensajes
-    echo -e " ${cor[5]} NewScriptADM Mod ChumoGH-ADM REFACTORIZADO "
-    barra de mensajes
-    echo -e "${cor[3]} DESENCADENANDO FICHEROS DEL SISTEMA "
+valid_fun () {
+    msg -bar
+    echo -e "${cor[2]}\n\033[1;37m  Script Patrocinado por: @ChumoGH - Henry Chumo" | pv -qL 12
+    msg -bar
+    echo -e "  ${cor[5]} NewScriptADM Mod ChumoGH-ADM REFACTORIZADO "
+    msg -bar
+    echo -e "${cor[3]}     DESENCADENANDO FICHEROS DEL SISTEMA "
     echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/menu && chmod +x /bin/menu
@@ -83,41 +83,41 @@ cd ${SCPdir} && ./menu' > /bin/cgh && chmod +x /bin/cgh
     echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/adm && chmod +x /bin/adm
-    barra de mensajes
-    [[ -e ${SCPdir}/menu_credito ]] && ress="$(cat ${SCPdir}/menu_credito) " || ress="NULL ( no encontrado ) "
-    echo -ne "${cor[2]}\n\033[1;37m REVENDEDOR: " | pv -qL 50 && sleep 1s && echo -e "\033[0;35m$ress" | pv -qL 50
+    msg -bar
+    [[ -e ${SCPdir}/menu_credito ]] && ress="$(cat ${SCPdir}/menu_credito) " || ress="NULL ( no found ) "
+    echo -ne "${cor[2]}\n\033[1;37m  RESELLER  : " | pv -qL 50 && sleep 1s && echo -e "\033[0;35m$ress" | pv -qL 50
     [[ -e ${SCPdir}/cabecalho ]] && bash ${SCPdir}/cabecalho --instalar
 }
 
-error_conex() {
-    claro&claro
-    barra de mensajes
-    echo -e "\e[3;31m MANUAL DE COMANDO DE CONEXIÓN FALLIDA: sudo apt update" | pv-qL 50
-    mensaje -barra3
-    echo -e "\e[5m\e[1;37m\e[48;5;235m =====>> ► ► ⚡ el_tioNel ⚡ ◄◄ <<===== \e[0m"
-    mensaje -barra3
-    echo -e "\033[1;33m EL PROBLEMA FUE UNA FALLA DE ACTUALIZACION DE SISTEMA "
-    dormir 12s
-    Salida 1
+error_conex () {
+    clear&&clear
+    msg -bar
+    echo -e "\e[3;31m   CONEXION FALLIDA  COMANDO MANUAL :  sudo apt  update" | pv -qL 50
+    msg -bar3
+    echo -e "\e[5m\e[1;37m\e[48;5;235m      =====>> ►►     ⚡ el_tioNel ⚡   ◄◄ <<=====   \e[0m"
+    msg -bar3
+    echo -e "\033[1;33m   EL PROBLEMA FUE UNA FALLA DE ACTUALIZACION DE SISTEMA "
+    sleep 12s
+    exit 1
 }
 
-invalid_key() {
-    barra de mensajes
-    echo -e "\e[3;31m La instalación no pudo completarse correctamente" | pv-qL 50
-    dormir 3
-    Salida 1
+invalid_key () {
+    msg -bar
+    echo -e "\e[3;31m  La instalacion no pudo completarse correctamente" | pv -qL 50
+    sleep 3
+    exit 1
 }
 
 # ============================================================
-# INSTALACION SIN LLAVE: descarga y monta todo desde GitHub
+# INSTALACION SIN KEY: descarga y monta todo desde GitHub
 # ============================================================
 funkey () {
-    claro&claro
-    mensaje -barra3
-    echo -e "\e[5m\e[1;37m\e[48;5;235m =====>> ► ► ⚡ el_tioNel ⚡ ◄◄ <<===== \e[0m"
-    mensaje -barra3
-    barra de mensajes
-    echo -e "\033[1;33m DESCARGANDO E INSTALANDO tioNelScript DESDE GITHUB ..."
+    clear&&clear
+    msg -bar3
+    echo -e "\e[5m\e[1;37m\e[48;5;235m      =====>> ►►  ⚡ el_tioNel ⚡  ◄◄ <<=====   \e[0m"
+    msg -bar3
+    msg -bar
+    echo -e "\033[1;33m   DESCARGANDO E INSTALANDO PandaScript DESDE GITHUB ..."
     [[ ! -d ${SCPdir} ]] && mkdir -p ${SCPdir}
     [[ ! -d /etc/adm-lite/slow ]] && mkdir -p /etc/adm-lite/slow
     [[ ! -d /etc/ADMcgh ]] && mkdir -p /etc/ADMcgh
@@ -128,9 +128,9 @@ funkey () {
         tar -xf adm-lite.tar.gz >/dev/null 2>&1
         chmod -R +x ${SCPdir} 2>/dev/null
         rm -f adm-lite.tar.gz
-    demás
-        echo " ! FALLO al descargar adm-lite.tar.gz"
-        clave_inválida
+    else
+        echo "   ! FALLO al descargar adm-lite.tar.gz"
+        invalid_key
     fi
 
     cd ${SCPdir}
@@ -143,10 +143,10 @@ funkey () {
     wget -q -O /bin/ejecutar/msg "${GITHUB_RAW}/Otros/ejecutar/msg" 2>/dev/null || cp -f ${SCPdir}/Otros/msg /bin/ejecutar/msg 2>/dev/null
     chmod +x /bin/ejecutar/msg 2>/dev/null
 
-    echo "Verificado【 ChumoGH" > /bin/ejecutar/exito
-    eco "v6=1.4.60" > /bin/ejecutar/v-new.log
-    eco "0" > /bin/ejecutar/uskill
-    eco "PandaHL001" > /etc/cghkey
+    echo "Verified【 ChumoGH" > /bin/ejecutar/exito
+    echo "v6=1.4.60" > /bin/ejecutar/v-new.log
+    echo "0" > /bin/ejecutar/uskill
+    echo "PandaHL001" > /etc/cghkey
     IP=$(wget -q -4 -O - http://ipv4.icanhazip.com 2>/dev/null | tr -d '[:space:]')
     [[ -z "$IP" ]] && IP=$(ip addr | grep 'inet ' | grep -v 127.0.0.1 | awk '{print $2}' | cut -d/ -f1 | head -1)
     echo "$IP" > /bin/ejecutar/IPcgh
@@ -155,9 +155,9 @@ funkey () {
     [[ -e ${SCPdir}/menu_credito ]] && cat ${SCPdir}/menu_credito > /bin/ejecutar/menu_credito || echo "ChumoGH" > /bin/ejecutar/menu_credito
     chmod +x /bin/ejecutar/* 2>/dev/null
 
-    eco "v6" > /etc/ADMcgh/v-local.log
-    eco "v6" > /etc/adm-lite/v-local.log
-    eco "v6=1.4.60" > /etc/adm-lite/local.txt
+    echo "v6" > /etc/ADMcgh/v-local.log
+    echo "v6" > /etc/adm-lite/v-local.log
+    echo "v6=1.4.60" > /etc/adm-lite/local.txt
 
     echo '#!/bin/bash
 SCPdir="/etc/adm-lite"
@@ -170,48 +170,48 @@ SCPdir="/etc/adm-lite"
 cd ${SCPdir} && ./menu' > /bin/adm && chmod +x /bin/adm
 
     chmod -R 755 ${SCPdir}
-    chmod +x ${SCPdir}/códigos de usuario ${SCPdir}/menu ${SCPdir}/ferramentas ${SCPdir}/cabecalho 2>/dev/null
-    barra de mensajes
-    echo -e "\033[1;32m >> tioNelScript DESCARGADO <<\033[0m"
-    barra de mensajes
+    chmod +x ${SCPdir}/usercodes ${SCPdir}/menu ${SCPdir}/ferramentas ${SCPdir}/cabecalho 2>/dev/null
+    msg -bar
+    echo -e "\033[1;32m           >> PandaScript DESCARGADO <<\033[0m"
+    msg -bar
 }
 
-actualizar_paquete() {
-    eco ""
+update_pak () {
+    echo ""
     [[ $(dpkg --get-selections|grep -w "pv"|head -1) ]] || apt install pv -y &> /dev/null
-    sistema operativo
-    echo -e "[ ! ] ESPERE UN MOMENTO [ ! ]"
+    os_system
+    echo -e "		[ ! ]  ESPERE UN MOMENTO  [ ! ]"
     [[ $(dpkg --get-selections|grep -w "lolcat"|head -1) ]] || apt-get install lolcat -y &>/dev/null
     [[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || apt-get install figlet -y &>/dev/null
-    eco ""
-    barra de mensajes
-    echo -e "\e[1;31m SISTEMA: \e[33m$distro $vercion \e[1;31m CPU: \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}')"
-    barra de mensajes
-    dpkg --configure -a > /dev/null 2>&1 && echo -e "\033[94m ${TTcent} INTENTANDO RECONFIGURAR UPDATER ${TTcent}" | pv -qL 80
-    barra de mensajes
-    echo -e "\033[94m ${TTcent} FECHA DE ACTUALIZACIÓN: $(date +"%d/%m/%Y") & HORA: $(date +"%H:%M") ${TTcent}" | pv -qL 80
+    echo ""
+    msg -bar
+    echo -e "\e[1;31m  SISTEMA:  \e[33m$distro $vercion \e[1;31m	CPU:  \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}')"
+    msg -bar
+    dpkg --configure -a > /dev/null 2>&1 && echo -e "\033[94m    ${TTcent} INTENTANDO RECONFIGURAR UPDATER ${TTcent}" | pv -qL 80
+    msg -bar
+    echo -e "\033[94m    ${TTcent} UPDATE DATE : $(date +"%d/%m/%Y") & TIME : $(date +"%H:%M") ${TTcent}" | pv -qL 80
     [[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || apt-get install net-tools -y &>/dev/null
     [[ $(dpkg --get-selections|grep -w "boxes"|head -1) ]] || apt-get install boxes -y &>/dev/null
     [[ $(dpkg --get-selections|grep -w "screen"|head -1) ]] || apt-get install screen -y &>/dev/null
     [[ $(dpkg --get-selections|grep -w "stunnel4"|head -1) ]] || apt-get install stunnel4 -y &>/dev/null
     [[ $(dpkg --get-selections|grep -w "python2"|head -1) ]] || apt-get install python2 -y &>/dev/null
-    eco ""
-    apt-get install software-properties-common -y > /dev/null 2>&1 && echo -e "\033[94m ${TTcent} INSTALANDO NUEVO PAQUETES ( S|P|C ) ${TTcent}" | pv -qL 80
-    eco ""
-    echo -e "\033[94m ${TTcent} PREPARANDO BASE RAPIDA INSTALL ${TTcent}" | pv-qL 80
-    barra de mensajes
-    eco "
-    claro&claro
-    devolver
+    echo ""
+    apt-get install software-properties-common -y > /dev/null 2>&1 && echo -e "\033[94m    ${TTcent} INSTALANDO NUEVO PAQUETES ( S|P|C )    ${TTcent}" | pv -qL 80
+    echo ""
+    echo -e "\033[94m    ${TTcent} PREPARANDO BASE RAPIDA INSTALL    ${TTcent}" | pv -qL 80
+    msg -bar
+    echo " "
+    clear&&clear
+    return
 }
 
-# ---------------- definiciones de mensajes y utilidades ----------------
+# ---------------- definiciones de msg y utilidades ----------------
 COLOR_VIOLETA='\033[38;5;129m'
 RESET='\033[0m'
 
-mensaje() {
-  colores locales="/etc/new-adm-color"
-  si [[ ! -e $colors ]]; entonces
+msg() {
+  local colors="/etc/new-adm-color"
+  if [[ ! -e $colors ]]; then
     COLOR[0]='\033[1;37m'
     COLOR[1]='\e[31m'
     COLOR[2]='\e[32m'
@@ -222,10 +222,10 @@ mensaje() {
     COLOR[7]='\033[1;49;95m'
     COLOR[8]='\033[1;49;96m'
     COLOR[9]='\033[38;5;129m'
-  demás
-    COL local=0
-    para cada número en $(cat $colors); hacer
-      caso $número en
+  else
+    local COL=0
+    for number in $(cat $colors); do
+      case $number in
         1)COLOR[$COL]='\033[1;37m';;
         2)COLOR[$COL]='\e[31m';;
         3)COLOR[$COL]='\e[32m';;
@@ -236,14 +236,14 @@ mensaje() {
         8)COLOR[$COL]='\033[1;49;95m';;
         9)COLOR[$COL]='\033[1;49;96m';;
       esac
-      dejar COL++
-    hecho
+      let COL++
+    done
   fi
 
   NEGRITO='\e[1m'
   SEMCOR='\e[0m'
 
-  caso $1 en
+  case $1 in
     -ne) cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
     -ama) cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
     -verm) cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}" ;;
@@ -253,24 +253,24 @@ mensaje() {
     -verd) cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
     -bra) cor="${COLOR[0]}${SEMCOR}" && echo -e "${cor}${2}${SEMCOR}" ;;
     -bar)
-      ANCHO=50
+      WIDTH=50
       echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${RESET}"
     ;;
-    -barra1)
-      ANCHO=50
+    -bar1)
+      WIDTH=50
       echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${RESET}"
     ;;
-    -barra2)
-      echo -e "${COLOR[4]}=======================================================${SEMCOR}"
+    -bar2)
+      echo -e "${COLOR[4]}=====================================================${SEMCOR}"
     ;;
-    -barra3)
-      eco -e "${COLOR_VIOLETA}━━━━━━━━━━━━━━━━━━━━━━━━━ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
+    -bar3)
+      echo -e "${COLOR_VIOLETA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
     ;;
     -bar4)
-      echo -e "${COLOR[5]}·························································${SEMCOR}"
+      echo -e "${COLOR[5]}•••••••••••••••••••••••••••••••••••••••••••••••••${SEMCOR}"
     ;;
-    -barra5)
-      ANCHO=50
+    -bar5)
+      WIDTH=50
       echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${RESET}"
     ;;
   esac
@@ -283,24 +283,24 @@ cor[3]="\033[1;37m"
 cor[4]="\033[1;36m"
 cor[5]="\033[1;33m"
 cor[6]="\033[1;35m"
-exportar -f mensaje
+export -f msg
 
 # ============================================================
-# EJECUCIÓN PRINCIPAL
+# EJECUCION PRINCIPAL
 # ============================================================
-claro&claro
-HORA_INICIO="$(fecha +%s)"
-barra de mensajes
-paquete de actualización
-claro&claro
+clear&&clear
+TIME_START="$(date +%s)"
+msg -bar
+update_pak
+clear&&clear
 funkey
-claro&claro
-barra de mensajes
-echo -e " Duracion $((($(fecha +%s)-$TIME_START)/60)) min."
-eco ""
-si [[ -e "$(which menu 2>/dev/null)" ]]; entonces
-    $(qué menú)
-demás
+clear&&clear
+msg -bar
+echo -e " Duracion $((($(date +%s)-$TIME_START)/60)) min."
+echo ""
+if [[ -e "$(which menu 2>/dev/null)" ]]; then
+    $(which menu)
+else
     echo -e " INSTALACION NO COMPLETADA CON EXITO !"
 fi
 echo " INSTALACION FINALIZADA "
